# Site settings
title: Read-the-LOD-paper
email: info@opsci.com
description: >- # this means to ignore newlines until "baseurl:"
  A reading club for relevant contemporary Linked Open Data and Semantic Web documents.
baseurl: "/rtlp" # the subpath of your site, e.g. /blog
url: "https://vliz-be-opsci.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: vliz-be-opsci
fixed_navbar: top

# Build settings
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
