# Site settings
title: Read the LOD
email: info@readthelod.org
description: A reading club for relevant contemporary Linked Open Data and Semantic Web documents.
#baseurl: "/"
#url: "https://readthelod.github.io/"
github_username: readthelod

fixed_navbar: top
show_sidebar: true

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  #- jekyll-rdf
# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
